{% set name = "watchfiles" %}
{% set version = "1.1.1" %}
{% set pytest_ignore = '--ignore="tests/test_cli.py"' %}
{% set pytest_ignore = pytest_ignore + ' --ignore="tests/test_filters.py"' %}
{% set pytest_ignore = pytest_ignore + ' --ignore="tests/test_run_process.py"' %}
{% set pytest_ignore = pytest_ignore + ' --ignore="tests/test_rust_notify.py"' %}  # [win]
{% set pytest_skip = "awatch_interrupt_raise" %}
{% set pytest_skip = pytest_skip + " or cli_help" %}
{% set pytest_skip = pytest_skip + " or test_ignore_permission_denied" %}  # [linux]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a173cb5c16c4f40ab19cecf48a534c409f7ea983ab8fed0741304a1c0a31b3f2

build:
  number: 0
  skip: true  # [py<39]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  entry_points:
    - watchfiles = watchfiles.cli:cli
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1  # [s390x] Known s390x `ld64.so` issue.

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - cargo-bundle-licenses =0.5.0
    - maturin >=0.14.16,<2
  run:
    - python
    - anyio >=3.0.0

test:
  source_files:
    - tests
    - pyproject.toml
  requires:
    - pip
    - pytest
    - pytest-timeout
    - pytest-mock
  imports:
    - watchfiles
  commands:
    - pip check
    - watchfiles -h
    # Requires dirty-equals, missing from defaults.
    # Test hangs indefinitely on linux
    - pytest {{ pytest_ignore }} -k "not ({{ pytest_skip }})" -v

about:
  home: https://watchfiles.helpmanual.io
  summary: Simple, modern and high performance file watching and code reload in python.
  description: |
    Watchfiles is a simple, modern and high performance file watching and code reload in python.
    Underlying file system notifications are handled by the Notify rust library.
  dev_url: https://github.com/samuelcolvin/watchfiles
  doc_url: https://watchfiles.helpmanual.io
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - davidbrochart
    - samuelcolvin
