{% set name = "watchfiles" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ae7c57ef920589a40270d5ef3216d693f4e6f8864d8fc8b6cb7885ca98ad2a61

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  entry_points:
    - watchfiles = watchfiles.cli:cli


requirements:
  build:
    - python
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python
    - anyio >=3.0.0,<4

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - watchfiles
  commands:
    - watchfiles -h

about:
  home: https://watchfiles.helpmanual.io
  summary: Simple, modern and high performance file watching and code reload in python.
  dev_url: https://github.com/samuelcolvin/watchfiles
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - davidbrochart
    - samuelcolvin
