{% set name = "watchfiles" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a173cb5c16c4f40ab19cecf48a534c409f7ea983ab8fed0741304a1c0a31b3f2

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  entry_points:
    - watchfiles = watchfiles.cli:cli
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - cargo-bundle-licenses =0.5.0
    - maturin >=0.14.16,<2
  run:
    - python
    - anyio >=3.0.0

# E   FileNotFoundError: [Errno 2] No such file or directory: 'docs/cli_help.txt'
# File docs/cli_help.txt was removed from the release tarball on PyPi and GitHub.
{% set deselect_tests = " --deselect=tests/test_docs.py::test_cli_help" %}
test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - watchfiles
  commands:
    - pip check
    - watchfiles -h
    - pytest -v {{ deselect_tests }}
  requires:
    - pip
    - pytest >=7.4.4
    # relax lower bound for pytest-timeout
    - pytest-timeout >=2.2.0
    - pytest-mock >=3.14.0
    - dirty-equals >=0.8.0

about:
  home: https://watchfiles.helpmanual.io
  summary: Simple, modern and high performance file watching and code reload in python.
  description: |
    Watchfiles is a simple, modern and high performance file watching and code reload in python.
    Underlying file system notifications are handled by the Notify rust library.
  dev_url: https://github.com/samuelcolvin/watchfiles
  doc_url: https://watchfiles.helpmanual.io 
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - davidbrochart
    - samuelcolvin
